#!/usr/bin/env bash
# =============================================================================
# ARK KB Pipeline — Quick-Start Script
# =============================================================================
# Checks environment, creates a Python virtual environment, installs all
# dependencies, and prints next steps.
#
# Usage:
#   bash quickstart.sh
# =============================================================================

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="${PROJECT_ROOT}/.venv"
REQUIREMENTS="${PROJECT_ROOT}/requirements.txt"

# ---------------------------------------------------------------------------
# Colours
# ---------------------------------------------------------------------------
if [[ -t 1 ]]; then
    C_RESET='\033[0m'
    C_BOLD='\033[1m'
    C_GREEN='\033[32m'
    C_YELLOW='\033[33m'
    C_RED='\033[31m'
    C_CYAN='\033[36m'
else
    C_RESET=''
    C_BOLD=''
    C_GREEN=''
    C_YELLOW=''
    C_RED=''
    C_CYAN=''
fi

info()  { printf "${C_GREEN}[INFO]${C_RESET}  %s\n" "$*"; }
warn()  { printf "${C_YELLOW}[WARN]${C_RESET}  %s\n" "$*"; }
err()   { printf "${C_RED}[ERR]${C_RESET}   %s\n" "$*" >&2; }
step()  { printf "\n${C_CYAN}▶ %s${C_RESET}\n" "$*"; }
done_msg() { printf "${C_GREEN}${C_BOLD}✔ %s${C_RESET}\n" "$*"; }

# ---------------------------------------------------------------------------
# 1. Check Python 3.11+
# ---------------------------------------------------------------------------
check_python() {
    step "Checking Python version"

    if ! command -v python3 &>/dev/null; then
        err "python3 is not installed. Please install Python 3.11 or newer."
        exit 1
    fi

    local py_version
    py_version=$(python3 --version 2>&1 | awk '{print $2}')
    info "Found Python ${py_version}"

    # Extract major.minor
    local major minor
    major=$(echo "$py_version" | cut -d. -f1)
    minor=$(echo "$py_version" | cut -d. -f2)

    if (( major < 3 )) || { (( major == 3 )) && (( minor < 11 )); }; then
        err "Python 3.11+ is required. You have ${py_version}."
        err "Upgrade Python or use pyenv / conda."
        exit 1
    fi

    done_msg "Python ${py_version} is acceptable (≥3.11)."
}

# ---------------------------------------------------------------------------
# 2. Create virtual environment
# ---------------------------------------------------------------------------
create_venv() {
    step "Creating virtual environment"

    if [[ -d "$VENV_DIR" ]]; then
        warn "Virtual environment already exists at ${VENV_DIR}."
        read -r -p "Recreate? [y/N] " answer || true
        if [[ "${answer:-}" =~ ^[Yy]$ ]]; then
            rm -rf "$VENV_DIR"
            python3 -m venv "$VENV_DIR"
            done_msg "Re-created virtual environment."
        else
            info "Re-using existing virtual environment."
        fi
    else
        python3 -m venv "$VENV_DIR"
        done_msg "Created virtual environment at ${VENV_DIR}."
    fi
}

# ---------------------------------------------------------------------------
# 3. Install dependencies
# ---------------------------------------------------------------------------
install_deps() {
    step "Installing Python packages"

    # Ensure pip is up to date
    "$VENV_DIR/bin/pip" install --quiet --upgrade pip

    # Core packages used by the pipeline
    local packages=(
        anthropic          # Anthropic LLM client
        httpx              # Modern HTTP client (used by downloaders)
        pydantic           # Data validation & settings
        beautifulsoup4     # HTML parsing for extractors
        trafilatura        # Article text extraction
        rich               # Terminal UI & progress bars
        tenacity           # Retry logic
        zstandard          # Compression for Stage 5
    )

    info "Installing: ${packages[*]}"
    "$VENV_DIR/bin/pip" install --quiet "${packages[@]}"

    done_msg "All packages installed."
}

# ---------------------------------------------------------------------------
# 4. Write a stub requirements.txt for reproducibility
# ---------------------------------------------------------------------------
write_requirements() {
    step "Writing requirements.txt"

    cat > "$REQUIREMENTS" <<'EOF'
# ARK KB Pipeline — Python dependencies
# Generated by quickstart.sh
# Install: pip install -r requirements.txt

anthropic>=0.21.0
httpx>=0.27.0
pydantic>=2.5.0
beautifulsoup4>=4.12.0
trafilatura>=1.6.0
rich>=13.0.0
tenacity>=8.2.0
zstandard>=0.22.0
EOF

    done_msg "Wrote ${REQUIREMENTS}."
}

# ---------------------------------------------------------------------------
# 5. Print next steps
# ---------------------------------------------------------------------------
print_next_steps() {
    step "Next Steps"

    printf "\n${C_BOLD}Your environment is ready!${C_RESET}\n\n"

    printf "  1. Activate the virtual environment:\n"
    printf "     ${C_CYAN}source ${VENV_DIR}/bin/activate${C_RESET}\n\n"

    printf "  2. Set your Anthropic API key (needed for Stage 2):\n"
    printf "     ${C_CYAN}export ANTHROPIC_API_KEY='sk-ant-...'${C_RESET}\n\n"

    printf "  3. Run the bootstrap to download all raw content:\n"
    printf "     ${C_CYAN}bash scripts/bootstrap-kb.sh${C_RESET}\n\n"

    printf "  4. After bootstrap completes, run the full pipeline:\n"
    printf "     ${C_CYAN}bash scripts/run-pipeline.sh${C_RESET}\n\n"

    printf "  (Optional) Override the staging directory:\n"
    printf "     ${C_CYAN}STAGING_DIR=/bigdisk/ark-kb bash scripts/bootstrap-kb.sh${C_RESET}\n\n"

    printf "  (Optional) Skip heavy sources to save time / disk:\n"
    printf "     ${C_CYAN}SKIP_SURVIVOR=1 SKIP_YOUTUBE=1 bash scripts/bootstrap-kb.sh${C_RESET}\n\n"

    done_msg "quickstart.sh complete — you're ready to bootstrap!"
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
main() {
    info "ARK KB Pipeline — Quick Start"
    info "Project root: ${PROJECT_ROOT}"

    check_python
    create_venv
    install_deps
    write_requirements
    print_next_steps
}

main "$@"
